### ISSUE TITLE
Can't find variable: Intl while using twitter Style.

### ISSUE THREAD

**Issue by sourabhkheterpal** [halt-hammerzeit/javascript-time-ago#3]
Fuzzy style works fine but twitter style gives me error.

**Comment by halt-hammerzeit** [comment]
Yeah, if you look at the README it says

> This package assumes that the `Intl` global object exists in the runtime. 

Which is the case in all latest browsers: http://caniuse.com/#search=Intl
And I'm also using a polyfill in my project.

That being said, if this whole thing is even working in your case then it's likely that Intl global variable is available and therefore it makes no sense that you're saying you have the "Intl undefined" error.
